[package]
name = "gfx-math"
version = "0.1.0"
authors = ["chee <dev_chee@outlook.com>"]
edition = "2018"
description = "A graphics math basic library."
keywords = ["graphic", "math"]

[features]

[dependencies]

[dependencies.serde]
optional = true
version = "1.0"
