[package]
name = "gfx-window"
version = "0.1.0"
authors = ["chee <dev_chee@outlook.com>"]
edition = "2018"
description = "A graphics basic window library."
keywords = ["graphics", "window"]

[dependencies.serde]
optional = true
version = "1.0"
